name: test

on:
  push:
    branches: [main]
    paths-ignore:
      - '*.md'
  pull_request:
    branches: [main]
    paths-ignore:
      - '*.md'

# bashを使うようにしてpipefailを有効にする
# https://docs.github.com/ja/actions/writing-workflows/workflow-syntax-for-github-actions#defaultsrunshell
defaults:
  run:
    shell: bash

jobs:
  test:
    runs-on: macos-15
    permissions:
      checks: write
    steps:
    # https://github.com/actions/runner-images/blob/main/images/macos/macos-14-Readme.md#xcode
    - name: Select Xcode version
      run: sudo xcode-select -s '/Applications/Xcode_16.app/Contents/Developer'
    - uses: actions/checkout@v4
    - name: test
      run: |
        xcodebuild -target macSKKTests -scheme macSKK DEVELOPMENT_TEAM= test | xcpretty
